### ISSUE TITLE
I am getting the following error with the 1.8-7q after uploading all the new files and running the sql statements

### ISSUE THREAD

**Issue by samoy2002** [pixeline/bugs#672] opened 2021-11-02 18:54 UTC
Unhandled Exception
Message:
Undefined index: temps_fait
Location:
/home/mbbizca/public_html/bugs/app/application/models/project/issue/comment.php on line 39
Stack Trace:
#0 /home/mbbizca/public_html/bugs/app/laravel/laravel.php(37): Laravel\Error::native(8, 'Undefined index...', '/home/mbbizca/p...', 39)
#1 /home/mbbizca/public_html/bugs/app/application/models/project/issue/comment.php(39): Laravel\{closure}(8, 'Undefined index...', '/home/mbbizca/p...', 39, Array)
#2 /home/mbbizca/public_html/bugs/app/application/controllers/project/issue.php(83): Project\Issue\Comment::create_comment(Array, Object(Project), Object(Project\Issue))
#3 [internal function]: Project_Issue_Controller->post_index('6', '90')
#4 /home/mbbizca/public_html/bugs/app/laravel/routing/controller.php(325): call_user_func_array(Array, Array)
#5 /home/mbbizca/public_html/bugs/app/laravel/routing/controller.php(285): Laravel\Routing\Controller->response('index', Array)
#6 /home/mbbizca/public_html/bugs/app/laravel/routing/controller.php(165): Laravel\Routing\Controller->execute('index', Array)
#7 /home/mbbizca/public_html/bugs/app/laravel/routing/route.php(153): Laravel\Routing\Controller::call('project.issue@i...', Array)
#8 /home/mbbizca/public_html/bugs/app/laravel/routing/route.php(124): Laravel\Routing\Route->response()
#9 /home/mbbizca/public_html/bugs/app/laravel/laravel.php(158): Laravel\Routing\Route->call()
#10 /home/mbbizca/public_html/bugs/index.php(18): require('/home/mbbizca/p...')
#11 {main}

**Comment by Patriboom** [comment] 2021-11-02 21:42
Hello, please let me know how did you abtain such result  ( the whole process like :
1) open new issue
2) comment it
3) comment it again, but this time with nothing in ... 

)


I tried again, but could not reproduce the problem.

Thanks.

**Comment by Patriboom** [comment] 2021-11-03 00:42
You may need this command in PhpMySQL

> ALTER TABLE projects_issues_comments ADD COLUMN temps_fait time DEFAULT NULL AFTER comment;

**Comment by samoy2002** [comment] 2021-11-03 00:49
Thank you.   I cannot test or give screenshots of where I am getting the errors till tomorrow morning.  It was a strange error as I was getting it at times as I hit go for a new issue and always when trying to link an image in a new issue.  On a side note, all the help you give and doing custom work, where do we donate to the project?

Mark

**Comment by Patriboom** [comment] 2021-11-03 03:19
Thanks for explination.  I could reproduce the issue creating an issue.  I'll fix it.

The patch will be available within few minutes.  Your clues helped.

I've never had offer for donation.  I think you have my email address, you can use it for that.  Thanks for offer.
The best reward will ever by to know that users are using it.

**Comment by Patriboom** [comment] 2021-11-03 03:21
release 7s is there with the patch for  "temps_plan" issue on new ticket's creation.

**Comment by samoy2002** [comment] 2021-11-03 15:10
Error
SQL query:


ALTER TABLE projects_issues_comments ADD COLUMN temps_fait time DEFAULT NULL AFTER comment
MySQL said: Documentation

#1060 - Duplicate column name 'temps_fait'

**Comment by Patriboom** [comment] 2021-11-03 15:21
Ok, good.  It says that the columns has already been defined.  That what I wanted to make sure of.
What were you doing when you received this notice ?   
- Was it installling the last update ? 
- Did you apply the command « ALTER TABLE projects_issues ... » directly in phpMyAdmin ?

**Comment by samoy2002** [comment] 2021-11-03 15:34
I did it directly in phpmyadmin.   For some reason I cannot upgrade software from within the administration tab.   It cannot connect for some reason. 

Mark

**Comment by Patriboom** [comment] 2021-11-03 15:43
Ok.
You may have message like « Your version is ahead of what the gitHub deposit offers » in Administration tab.  That could explain you can not update database automatically.  It will come back to normal soon, just after those little fixes we are doing now.

Those MySQL commands will be part of the coming update.
Just make sure all is set properly with that: 
> ALTER TABLE projects_issues_comments MODIFY COLUMN temps_fait_fin datetime DEFAULT NULL;
> ALTER TABLE projects_issues_comments MODIFY COLUMN temps_fait_deb datetime DEFAULT NULL;
> ALTER TABLE projects_issues_comments MODIFY COLUMN temps_fait smallint(4) DEFAULT 1;

**Comment by Patriboom** [comment] 2021-11-04 14:01
samoy2002 wrote: 
>On a side note, all the help you give and doing custom work, where do we donate to the project?

If you're scuba diver, you can help me on another project.

**Closed** 2021-11-04 17:10 UTC
Labels: ¿ Fixed ?, If OK -> Close it, Locally tested and fine
