### ISSUE TITLE
Doesn't send email

### ISSUE THREAD

**Issue by Hazaels** [pixeline/bugs#34] opened 2016-11-02 10:14 UTC
When a new issue is created or updated BUGS doesn't send the email to the people involved in the ISSUE (assigned to).

Such feature is listed on the README.MD file as:

> Reliable: you get a warning email whenever someone comments, closes or assigns you a bug ticket (unless you did it to yourself, you sick mind).

How to fix or to configure it?

Is there any info anywhere? 

Thanks

**Comment by Qatan** [comment] 2016-11-10 14:18
Sorry... but I am really interested... 
Any news?

**Comment by pixeline** [comment] 2016-11-10 15:43
Check this first:
1. Are you sure the hosting server is able to send emails? Try using the mail() function in a test script.
2. the system does not send emails to yourself for changes you made yourself

**Comment by Qatan** [comment] 2016-11-10 17:11
Hi Alexandre,

The hosting server is able to send email (tested the mail() function)
The issues are being created by me but assigned to other user (that has a different email account).
I will recheck to see why it doesn’t work for me... 
If I can’t make it to work then can I give you access to it so you could check for me?
Thanks for your prompt reply.

**Comment by pixeline** [comment] 2016-11-10 17:24
Sorry, I don't have the time to support this project anymore. Maybe someone in here will?

**Comment by Qatan** [comment] 2016-11-10 19:02
No problem Alexandre.
Anyway I am very thankful for this nice project.
I am using it and I am very satisfied with it.
Thank you!

**Comment by julianatienza** [comment] 2016-11-24 11:18
It's strange because if there was a common issue about mail, the user creation mail wouldn't be sent (but this mail is sent). 

My Php knowledgment is very very basic but i would like to help with this project because it's really useful. 

Also I've seen pending code pull request. If somebody wanted to continue this project i'd like to help with (at least) testing or configuration tasks.

**Comment by Patriboom** [comment] 2016-11-25 18:47
Did anyone work on the PHP code about the present issue (emailing) ? 

If not, I accept to have a look on that.

But I'm newbie with github and unable to manage that for now.  That's why i had to open a new deposit  at  https://github.com/Patriboom/bugs  

I can trade work on email issue against explination on how to use github: pull request, update and so on.

**Comment by Patriboom** [comment] 2016-11-27 04:14
@Hazaels  and  @julianatienza , please, 
give me more infos about what works and what doesn't in the email thing.

**Comment by julianatienza** [comment] 2016-11-27 09:08
Nowaday, with the code of this project and not the forked one (i've still not tested it), email is only sent when one issue is assigned or reassigned to you. 

But, for example, if you're the creator of the issue and one developer close it or change state of issue, there is not any kind of notification or email...

**Comment by Hazaels** [comment] 2016-11-27 10:59
Hi,

Sorry for the silence.
I will make a few tests and I will report what is going on.
Thank you for the willingness to help

**Comment by Hazaels** [comment] 2016-11-27 16:58
What I found out is that the emails are being sent. 
The problem is the way they are sent... it is easily interpreted as SPAM by many common email systems in many hosting companies so the emails were being taken as SPAM with a score of 7.9 (that is pretty high). It includes GMail. 

**Here is the Mail Delivery System message:**  _"Sorry, this message has been identified as SPAM (7.9)"_

There is a way to do it to avoid such problem because I use a CMS made of PHP and it sends emails without problem. I could try to copy the part of the code that sends email from the CMS and try to patch on the BUGS code but since I am not very good in PHP I would prefer someone to look into it.

Anyone available that could try to improve the mail send part to avoid it being taken as SPAM?

**Comment by julianatienza** [comment] 2016-11-27 17:07
Ok. Now i have understood. The problem is in the hosting not in the client side

**Comment by Hazaels** [comment] 2016-11-28 10:22
I read the "Projects" section and I wanted to complete the information but couldn't find a way to do so I will post it here:

1) The email system is supposed to work (send email) and to not be considered SPAM.
2) It should be triggered by any changes, comment that is written or change in status.
3) Should be sent to the project manager and to the assigned person.
4) Should be sent immediately (after it is triggered).
5) Would be interesting to show a simple notification that the email was sent (or an error message if it wasn't).

Bugs looks nice, runs well, is fast and it is fluid but needs some improvements.
I am sorry that I can't help with the code...

**Comment by pixeline** [comment] 2016-11-28 10:25
re: SPAM issue. Entirely related to the server on which Bugs is running on. Add a SPF record, or better, use a dedicated smtp server that is meant to do that (www.mailgun.com for example)

**Comment by Hazaels** [comment] 2016-11-28 10:52
I will check about that and I will write down the results.

I didn't suspect about it because I use a couple of CMS in PHP and they can send email from the same server on which Bugs is running without issues. 

I will also give a look in MailGun - thanks for the suggestion.

**Comment by Patriboom** [comment] 2016-12-02 00:15
So ...

> Nowaday, with the code of this project and not the forked one (i've still not tested it), email is only sent when one issue is assigned or reassigned to you.
> But, for example, if you're the creator of the issue and one developer close it or change state of issue, there is not any kind of notification or email... Same situation for new comments when added.


@julianatienza wrote is still true and it is the only problem with email
Is that what you find out also, @Hazaels  ?

**Comment by Patriboom** [comment] 2016-12-02 00:28
@julianatienza  &  @Hazaels 
I try to configure my Bugs program to work on this issue.
What have I to write in 'sendmail' => array('path' => ''), line
( out of config.app.php  file ?  )

**Comment by Patriboom** [comment] 2016-12-02 01:14
I tried many things:  create new issue, comment an existing issue and so on, but not a single email have been sent to me.
Please help me to configure my email system properly on bugs
Here my config:

	'mail' => array(
		'from' => array(
			'name' => 'My name',
			'email' => 'adresse@domain.net',
		),
		/**
		 * Transport Settings
		 * Transport settings if using mail or SMTP
		 */
		'transport' => 'SMTP',
		'sendmail' => array('path' => ''),
		'smtp' => array(
			'server' => 'server.domain.com',
			'port' => 465,
			/* 
			* Encryption support, SSL/TLS, used with gmail servers
			* Default: blank
			*/
			'encryption' => 'SSL',
			'username' => 'user@domain.net',
			'password' => 'Properpassword',
		),
	),

**Comment by julianatienza** [comment] 2016-12-02 06:31
In my local server environment i've configured my Gmail Account with mail system of linux SO... so when somebody invoke mail in php with localhost as machine, it must send mail without extra config.
Which is your operating System?

**Comment by julianatienza** [comment] 2016-12-02 08:04
Ok. If you don't want to use mail as transport, and you wanted to config smtp instead, this is the config that works with me:

  ```
   'mail' => array(
                'from' => array(
                        'name' => 'xxxx',
                        'email' => 'xxxx@gmail.com',
                ),
                'transport' => 'smtp',
                /**
                 * Transport Settings
                 *
                 * Transport settings if using sendmail or SMTP
                 */
                'sendmail' => array(
                        'path' => ''
                ),
                'smtp' => array(
                        'server' => 'smtp.gmail.com',                       
                        'port' => 587,
                        'encryption' => 'tls',
                        'username' => 'xxxx',
                        'password' => '****',
                ),
```



But i needed to change manually one file (protected attribute) in order to solve this collateral bug with PHP versions and Swift Transport libs used in this project: 
http://stackoverflow.com/questions/26020949/swiftmailer-error-undefined-property-swift-transport-streambuffer-sequence

**Comment by Patriboom** [comment] 2016-12-02 14:03
Ok, thanks @julianatienza 
I worked only on config.app.php file and email system is working.
I only changed uppercases to lowercases and ... ya.

Such is my config now, if ever it can help someone:

	'mail' => array(
		'from' => array(
			'name' => 'Author name',
			'email' => 'name@domain.net',
		),
		/**
		 * Transport Settings
		 * Transport settings if using mail or smtp
                 *  It most be lower case
		 */
		'transport' => 'smtp',
		'sendmail' => array('path' => ''),
		'smtp' => array(
			'server' => 'host.domain.com',
			'port' => 465,
			/* 
			* Encryption support, SSL/TLS, used with gmail servers
			* Default: blank; if you write something it must be lowercase
			*/
			'encryption' => 'ssl',
			'username' => 'name@domain.ext',
			'password' => 'xyzxyz',
		),
	),

**Comment by Patriboom** [comment] 2016-12-02 14:20
@Hazaels   I made mine to work properly without any change in PHP code.  It was only my config file which was wrong.
To fix my config file, i only set  SMTP and TLS in lower case  (  smtp   and tls ) in the config.

**Comment by Hazaels** [comment] 2016-12-02 14:39
@pixeline 
I don't think it is SPAM issue - I already configured SPF on the hosting (nice to know about that - thank you)
MailGun is over complicated (I gave up in the midst of the whole process...)

I am starting to think the problem is not with BUGS but with my own configuration.

Thanks for @julianatienza and @Patriboom for sharing your progress.
I will take more time and do some tests to find what is the problem

**Comment by Patriboom** [comment] 2016-12-02 15:10
@Hazaels   ... many spam hunters look at « Where from » to tag a mail as SPAM
Many SPAM are written from  a false  yourself
So, you may change this part's values:

	'from' => array(
		'name' => 'Author name',
		'email' => 'name@domain.net',
	),
On mine:  name is "Bugs programm"  
It's not my name.
You can go further changing the email value for somthing different of yours.

**Comment by Patriboom** [comment] 2016-12-02 15:11
I will not work on that until I receive news form users.
For now, it seams to work properly.

**Comment by julianatienza** [comment] 2016-12-02 17:44
Now i have been able to test in local, mails are being sent Ok.

**Closed** 2016-12-03 15:54 UTC
Labels: bug, enhancement, help wanted
