### ISSUE TITLE
Tags-table missing after installation

### ISSUE THREAD

**Issue by leo-graf** [pixeline/bugs#14] opened 2015-03-25 21:49 UTC
PHP Version: 5.5.9-1ubuntu4.7
MySQL Version: 5.5.41

The Tags-table was missing after installation. It worked when I imported "MySQL DB Schema.sql" manually, before installation!

latest commit 97d59522c1

**Comment by melanholly** [comment] 2015-06-02 14:15
There are some issues in the installation script. When I've imported manually **MySQL DB Schema.sql** from the downloaded folder and everything worked as expected

**Comment by fnadde42** [comment] 2015-07-04 10:14
I can confirm that @melanholly solution works for me too. The install script needs some love...

**Comment by pixeline** [comment] 2015-07-12 21:01
Fixed in upcoming 1.5

**Closed by pixeline** 2015-07-12 21:01 UTC
