### ISSUE TITLE
#98 :   Error on bugs/administration/users/add

### ISSUE THREAD

**Issue by rfsales** [pixeline/bugs#98] opened 2017-02-23 20:11 UTC
After first login I could not create a new user:

Unhandled Exception
Message:

Undefined property: Swift_Transport_StreamBuffer::$_sequence

Location:

/home/www//bugs/app/vendor/Swift/lib/classes/Swift/Transport/StreamBuffer.php on line 236

Stack Trace:

#0 /home/www//bugs/app/laravel/laravel.php(42): Laravel\Error::native(8, 'Undefined prope...', '/home/www//...', 236)
#1 /home/www//bugs/app/vendor/Swift/lib/classes/Swift/Transport/StreamBuffer.php(236): Laravel\{closure}(8, 'Undefined prope...', '/home/www//...', 236, Array)
#2 /home/www//bugs/app/vendor/Swift/lib/classes/Swift/ByteStream/AbstractFilterableInputStream.php(165): Swift_Transport_StreamBuffer->_commit('EHLO sisani.com...')
#3 /home/www//bugs/app/vendor/Swift/lib/classes/Swift/ByteStream/AbstractFilterableInputStream.php(81): Swift_ByteStream_AbstractFilterableInputStream->_doWrite('EHLO sisani.com...')
#4 /home/www//bugs/app/vendor/Swift/lib/classes/Swift/Transport/AbstractSmtpTransport.php(300): Swift_ByteStream_AbstractFilterableInputStream->write('EHLO sisani.com...')
#5 /home/www//bugs/app/vendor/Swift/lib/classes/Swift/Transport/EsmtpTransport.php(224): Swift_Transport_AbstractSmtpTransport->executeCommand('EHLO sisani.com...', Array, Array)
#6 /home/www//bugs/app/vendor/Swift/lib/classes/Swift/Transport/EsmtpTransport.php(267): Swift_Transport_EsmtpTransport->executeCommand('EHLO sisani.com...', Array)
#7 /home/www//bugs/app/vendor/Swift/lib/classes/Swift/Transport/AbstractSmtpTransport.php(124): Swift_Transport_EsmtpTransport->_doHeloCommand()
#8 /home/www//bugs/app/vendor/Swift/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#9 /home/www//bugs/app/application/libraries/mail.php(68): Swift_Mailer->send(Object(Swift_Message))
#10 /home/www//bugs/app/application/models/user.php(329): Mail::send_email(Object(Swift_Message), 'thiago.ramos@ve...', Object(Laravel\Lang))
#11 /home/www//bugs/app/application/controllers/administration/users.php(26): User::add_user(Array)
#12 [internal function]: Administration_Users_Controller->post_add()
#13 /home/www//bugs/app/laravel/routing/controller.php(325): call_user_func_array(Array, Array)
#14 /home/www//bugs/app/laravel/routing/controller.php(285): Laravel\Routing\Controller->response('add', Array)
#15 /home/www//bugs/app/laravel/routing/controller.php(165): Laravel\Routing\Controller->execute('add', Array)
#16 /home/www//bugs/app/laravel/routing/route.php(153): Laravel\Routing\Controller::call('administration....', Array)
#17 /home/www//bugs/app/laravel/routing/route.php(124): Laravel\Routing\Route->response()
#18 /home/www//bugs/app/laravel/laravel.php(164): Laravel\Routing\Route->call()
#19 /home/www//bugs/index.php(20): require('/home/www//...')
#20 {main}

**Comment by Patriboom** [comment] 2017-02-23 20:41
I have no clue how to fix that.
Help, anyone?

**Comment by rfsales** [comment] 2017-02-23 20:55
Actually after looking, the user was created, but it printed that error too.

**Comment by Patriboom** [comment] 2017-02-24 14:02
rfsales wrote:

> I got another error:

Unhandled Exception
Message:

Undefined property: Swift_Transport_StreamBuffer::$_sequence

Location:

/home/www/bugs/app/vendor/Swift/lib/classes/Swift/Transport/StreamBuffer.php on line 236

Stack Trace:

#0 /home/www/bugs/app/laravel/laravel.php(42): Laravel\Error::native(8, 'Undefined prope...', '/home/www/...', 236)
#1 /home/www/bugs/app/vendor/Swift/lib/classes/Swift/Transport/StreamBuffer.php(236): Laravel\{closure}(8, 'Undefined prope...', '/home/www/...', 236, Array)
#2 /home/www/bugs/app/vendor/Swift/lib/classes/Swift/ByteStream/AbstractFilterableInputStream.php(165): Swift_Transport_StreamBuffer->_commit('EHLO sisani.com...')
#3 /home/www/bugs/app/vendor/Swift/lib/classes/Swift/ByteStream/AbstractFilterableInputStream.php(81): Swift_ByteStream_AbstractFilterableInputStream->_doWrite('EHLO sisani.com...')
#4 /home/www/bugs/app/vendor/Swift/lib/classes/Swift/Transport/AbstractSmtpTransport.php(300): Swift_ByteStream_AbstractFilterableInputStream->write('EHLO sisani.com...')
#5 /home/www/bugs/app/vendor/Swift/lib/classes/Swift/Transport/EsmtpTransport.php(224): Swift_Transport_AbstractSmtpTransport->executeCommand('EHLO sisani.com...', Array, Array)
#6 /home/www/bugs/app/vendor/Swift/lib/classes/Swift/Transport/EsmtpTransport.php(267): Swift_Transport_EsmtpTransport->executeCommand('EHLO sisani.com...', Array)
#7 /home/www/bugs/app/vendor/Swift/lib/classes/Swift/Transport/AbstractSmtpTransport.php(124): Swift_Transport_EsmtpTransport->_doHeloCommand()
#8 /home/www/bugs/app/vendor/Swift/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#9 /home/www/bugs/app/application/libraries/mail.php(68): Swift_Mailer->send(Object(Swift_Message))
#10 /home/www/bugs/app/application/models/project/issue.php(597): Mail::send_email(Object(Swift_Message), 'edilycesar@gmai...', 'New issue "Disp...')
#11 /home/www/bugs/app/application/controllers/project/issue.php(36): Project\Issue::create_issue(Array, Object(Project))
#12 [internal function]: Project_Issue_Controller->post_new('1')
#13 /home/www/bugs/app/laravel/routing/controller.php(325): call_user_func_array(Array, Array)
#14 /home/www/bugs/app/laravel/routing/controller.php(285): Laravel\Routing\Controller->response('new', Array)
#15 /home/www/bugs/app/laravel/routing/controller.php(165): Laravel\Routing\Controller->execute('new', Array)
#16 /home/www/bugs/app/laravel/routing/route.php(153): Laravel\Routing\Controller::call('project.issue@n...', Array)
#17 /home/www/bugs/app/laravel/routing/route.php(124): Laravel\Routing\Route->response()
#18 /home/www/bugs/app/laravel/laravel.php(164): Laravel\Routing\Route->call()
#19 /home/www/bugs/index.php(20): require('/home/www/...')
#20 {main}

**Comment by Patriboom** [comment] 2017-02-24 14:06
May you explain when such error occurs please ? 
Anyone has such error ?   If so ... when ?

**Comment by rfsales** [comment] 2017-02-24 18:05
Check this video:

https://vimeo.com/205584707

**Comment by Patriboom** [comment] 2017-02-24 18:27
I just replicated the exact same as we see in your video and reach no error.

You know, you can enjoy your software in spanish.  You can assign differente language for each user.

**Comment by Patriboom** [comment] 2017-02-24 18:32
Have you checked your directories rights ? 
try this in consol:
chown -R vectorco:www-data /home/vectorco/public_html/sisani.com.br./bugs/

**Comment by rfsales** [comment] 2017-02-24 18:41
About the language, I'm translating to Portuguese Brazil, but didn't find where to include in the initial listbox: http://prntscr.com/ecxhws do you know where I can add it?

**Comment by Patriboom** [comment] 2017-02-24 18:54
Please check your line 165   (file app/vendor/Swift/lib/classes/Swift/Transport/StreamBuffer.php )
It should be:

  public function readLine($sequence)


-------------------------


What do you mean  « intial listbox »  ?  
I guess, you're looking for ./app/application/views/layouts/login.php

If so, the page is reading for all language sub-directories.
To make portuguese-brazil appear, you have to create a new sub-dir named according to the language you what to show up.

**Comment by Patriboom** [comment] 2017-02-24 18:59
When you translation will be done, please send it to patrick arobas cartefoi dot net 
I'll include it into the whole package.

**Comment by Hazaels** [comment] 2017-03-03 10:20
I have exact the same issue: (happens all the time...)
And I checked the line 165 as you mentioned and what is there is:   `public function readLine($sequence)`

Here is the error:

```
Unhandled Exception
Message:
Undefined property: Swift_Transport_StreamBuffer::$_sequence
Location:
/home3/sysbasef/public_html/bugs/app/vendor/Swift/lib/classes/Swift/Transport/StreamBuffer.php on line 236
Stack Trace:
#0 /home3/sysbasef/public_html/bugs/app/laravel/laravel.php(42): Laravel\Error::native(8, 'Undefined prope...', '/home3/sysbasef...', 236)
#1 /home3/sysbasef/public_html/bugs/app/vendor/Swift/lib/classes/Swift/Transport/StreamBuffer.php(236): Laravel\{closure}(8, 'Undefined prope...', '/home3/sysbasef...', 236, Array)
#2 /home3/sysbasef/public_html/bugs/app/vendor/Swift/lib/classes/Swift/ByteStream/AbstractFilterableInputStream.php(165): Swift_Transport_StreamBuffer->_commit('EHLO www.asysbas...')
#3 /home3/sysbasef/public_html/bugs/app/vendor/Swift/lib/classes/Swift/ByteStream/AbstractFilterableInputStream.php(81): Swift_ByteStream_AbstractFilterableInputStream->_doWrite('EHLO www.asysbas...')
#4 /home3/sysbasef/public_html/bugs/app/vendor/Swift/lib/classes/Swift/Transport/AbstractSmtpTransport.php(300): Swift_ByteStream_AbstractFilterableInputStream->write('EHLO www.asysbas...')
#5 /home3/sysbasef/public_html/bugs/app/vendor/Swift/lib/classes/Swift/Transport/EsmtpTransport.php(224): Swift_Transport_AbstractSmtpTransport->executeCommand('EHLO www.asysbas...', Array, Array)
#6 /home3/sysbasef/public_html/bugs/app/vendor/Swift/lib/classes/Swift/Transport/EsmtpTransport.php(268): Swift_Transport_EsmtpTransport->executeCommand('EHLO www.asysbas...', Array)
#7 /home3/sysbasef/public_html/bugs/app/vendor/Swift/lib/classes/Swift/Transport/AbstractSmtpTransport.php(124): Swift_Transport_EsmtpTransport->_doHeloCommand()
#8 /home3/sysbasef/public_html/bugs/app/vendor/Swift/lib/classes/Swift/Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#9 /home3/sysbasef/public_html/bugs/app/application/libraries/mail.php(68): Swift_Mailer->send(Object(Swift_Message))
#10 /home3/sysbasef/public_html/bugs/app/application/models/project/issue.php(597): Mail::send_email(Object(Laravel\View), 'john@asysb...', 'New issue "Old ...')
#11 /home3/sysbasef/public_html/bugs/app/application/controllers/project/issue.php(36): Project\Issue::create_issue(Array, Object(Project))
#12 [internal function]: Project_Issue_Controller->post_new('1')
#13 /home3/sysbasef/public_html/bugs/app/laravel/routing/controller.php(325): call_user_func_array(Array, Array)
#14 /home3/sysbasef/public_html/bugs/app/laravel/routing/controller.php(285): Laravel\Routing\Controller->response('new', Array)
#15 /home3/sysbasef/public_html/bugs/app/laravel/routing/controller.php(165): Laravel\Routing\Controller->execute('new', Array)
#16 /home3/sysbasef/public_html/bugs/app/laravel/routing/route.php(153): Laravel\Routing\Controller::call('project.issue@n...', Array)
#17 /home3/sysbasef/public_html/bugs/app/laravel/routing/route.php(124): Laravel\Routing\Route->response()
#18 /home3/sysbasef/public_html/bugs/app/laravel/laravel.php(164): Laravel\Routing\Route->call()
#19 /home3/sysbasef/public_html/bugs/index.php(20): require('/home3/sysbasef...')
#20 {main}
```

**Comment by Patriboom** [comment] 2017-03-11 12:55
Hello all, 
after an other issue, I started think that : the problems are from the installation process.
Any « old » user find no bug.  
Let try to figure out what goes wrong during the installation, probably around the « sequence », « duration » and other variables like those.
I seems that some constants and variables are not properly integrated.

**Comment by Patriboom** [comment] 2017-03-11 13:05
rfsales: please open a  new issue about your language translation.

**Comment by Hazaels** [comment] 2017-03-11 23:03
It is true... only happens in new installations
I had installed it time ago and never had that error.
Now I installed again and I got the error all the time.
Note: It is in the exactly same web hosting so it tells me that the problem is not with the hosting, PHP version, MySQL, Apache, etc... but in Bugs.

Any help is very welcome!

**Comment by Patriboom** [comment] 2017-03-12 04:47
Ok, thanks for your comment back.
Are you able to use the tools anyway ? 
I'm now revewing the entire install process.  While doing so, I also prepare php code to permit translations.

**Comment by thehamzan6** [comment] 2017-03-12 08:46
I tried to recreate this error and indeed it is an issue.

`Unhandled Exception
Message:

Undefined property: Swift_Transport_StreamBuffer::$_sequence

Location:

D:\Server\eds-www\tracker\app\vendor\Swift\lib\classes\Swift\Transport\StreamBuffer.php on line 236

Stack Trace:

#0 D:\Server\eds-www\tracker\app\laravel\laravel.php(42): Laravel\Error::native(8, 'Undefined prope...', 'D:\\Server\\eds-w...', 236)
#1 D:\Server\eds-www\tracker\app\vendor\Swift\lib\classes\Swift\Transport\StreamBuffer.php(236): Laravel\{closure}(8, 'Undefined prope...', 'D:\\Server\\eds-w...', 236, Array)
#2 D:\Server\eds-www\tracker\app\vendor\Swift\lib\classes\Swift\ByteStream\AbstractFilterableInputStream.php(165): Swift_Transport_StreamBuffer->_commit('EHLO [127.0.0.1...')
#3 D:\Server\eds-www\tracker\app\vendor\Swift\lib\classes\Swift\ByteStream\AbstractFilterableInputStream.php(81): Swift_ByteStream_AbstractFilterableInputStream->_doWrite('EHLO [127.0.0.1...')
#4 D:\Server\eds-www\tracker\app\vendor\Swift\lib\classes\Swift\Transport\AbstractSmtpTransport.php(300): Swift_ByteStream_AbstractFilterableInputStream->write('EHLO [127.0.0.1...')
#5 D:\Server\eds-www\tracker\app\vendor\Swift\lib\classes\Swift\Transport\EsmtpTransport.php(224): Swift_Transport_AbstractSmtpTransport->executeCommand('EHLO [127.0.0.1...', Array, Array)
#6 D:\Server\eds-www\tracker\app\vendor\Swift\lib\classes\Swift\Transport\EsmtpTransport.php(268): Swift_Transport_EsmtpTransport->executeCommand('EHLO [127.0.0.1...', Array)
#7 D:\Server\eds-www\tracker\app\vendor\Swift\lib\classes\Swift\Transport\AbstractSmtpTransport.php(124): Swift_Transport_EsmtpTransport->_doHeloCommand()
#8 D:\Server\eds-www\tracker\app\vendor\Swift\lib\classes\Swift\Mailer.php(79): Swift_Transport_AbstractSmtpTransport->start()
#9 D:\Server\eds-www\tracker\app\application\libraries\mail.php(68): Swift_Mailer->send(Object(Swift_Message))
#10 D:\Server\eds-www\tracker\app\application\models\user.php(329): Mail::send_email(Object(Laravel\View), 'test@test.com', Object(Laravel\Lang))
#11 D:\Server\eds-www\tracker\app\application\controllers\administration\users.php(26): User::add_user(Array)
#12 [internal function]: Administration_Users_Controller->post_add()
#13 D:\Server\eds-www\tracker\app\laravel\routing\controller.php(325): call_user_func_array(Array, Array)
#14 D:\Server\eds-www\tracker\app\laravel\routing\controller.php(285): Laravel\Routing\Controller->response('add', Array)
#15 D:\Server\eds-www\tracker\app\laravel\routing\controller.php(165): Laravel\Routing\Controller->execute('add', Array)
#16 D:\Server\eds-www\tracker\app\laravel\routing\route.php(153): Laravel\Routing\Controller::call('administration....', Array)
#17 D:\Server\eds-www\tracker\app\laravel\routing\route.php(124): Laravel\Routing\Route->response()
#18 D:\Server\eds-www\tracker\app\laravel\laravel.php(164): Laravel\Routing\Route->call()
#19 D:\Server\eds-www\tracker\index.php(20): require('D:\\Server\\eds-w...')
#20 {main}`

**Comment by Hazaels** [comment] 2017-03-12 09:22
I can’t use it... specially with a team (that’s the main purpose of it, isn’t it?)
I ended up with dozens of duplicated issues because they think it is not registering so they double entry the issues.
In the end they give up and I am flooded with emails of users complaining about it.
If I don’t find a solution for the bug I will have to do something – that is – find other tool that works.
I would not try to do the translation thing right now... my priority would be to fix the bugs first.

Thank you for your interest.

**Comment by Patriboom** [comment] 2017-03-12 12:20
Thanks for your comments.
I'm working with this new version and it works well.
For now, I found issue during the install process: doesn't install the database properly.  I'm on that, it means:  step one.

**Comment by thehamzan6** [comment] 2017-03-12 18:23
Might I as well make a minor suggestion, under project -> open issues, the time the issue was opened is missing a space between time and ago.

**Comment by Patriboom** [comment] 2017-03-12 19:23
Thanks for idea, i'll check overt that.  Next time, please, open a new issue for such suggestion.

**Comment by Patriboom** [comment] 2017-03-13 03:25
Hello all, 

I reviewed the entire install process and prepared the whole thing for translation.
Now I'm testing a brand new Bugs.  I've installed a new one from scratch:
- gave database name
- gave admin user
- created first project
- created first issue into this first project.  Before assigning default assignment
- create second issue after defined default assignement
All that with no error.

My first error accured when I tried to assign an issue to another user.
I've never expected that, no one said me that!
Ok, let work on that now.

**Comment by Patriboom** [comment] 2017-03-13 03:48
Hello all!
back on investigation and question.
This issue occurs both when you create new ticket and assign it to other user than you AND when you edit a ticket and assing it to an other user than yourself.  Right ? 

For now, the only difference i see, is the mailing notice sent to the other user.
That's my first hypothesis.
May you check you mailing configuration please, and let me know if such corrections make the job ?

**Comment by Patriboom** [comment] 2017-03-13 03:57
Ok, 

I've found something.
I'm running out of time; I have to go bed, tomorrow work, so I give you a version - for now - which works good BUT DO NOT SEND any mail to the new assignee.

**Comment by Patriboom** [comment] 2017-03-13 04:10
> Might I as well make a minor suggestion, under project -> open issues, the time the issue was opened 
> is missing a space between time and ago.

Fixed.  I could never find it because i don't use english.
Please be super-acurate in such situation, you can even send image or video to shorten my search.

**Comment by Patriboom** [comment] 2017-03-14 01:48
Good news, everybody!
Your favorite Bugs system is now able to send mails and doesn't bugs anymore when you change the assignee.

There's some more to do, I know.

- It works ONLY with smtp message system
- It shows the wrong new assignee in the « done tasks » list  AND in issue history.

I will close this issue somewhen durint the current week.
If you want me to look over what is missing ( up list ) or other thing about that, please open new ticket here.

**Comment by Patriboom** [comment] 2017-03-14 02:00
# @rfsales @Hazaels @thehamzan6 
Please check it.
It tested it some few times but it is never the same in real world.
#111

**Comment by Hazaels** [comment] 2017-03-14 11:18
I will test it... by the way how do you do to use the lastest version over the old one without loosing your database?
Do I have to recreate everything? 
Just wondering...

**Comment by Patriboom** [comment] 2017-03-14 21:32
To replace version
1) backup your config.app.php file  (from Bugs's main directory to somewhere you'll remember)
2) copy new files over the old ones
3) copy back you config.app.php from you backup directory to the Bugs' main directory.
Nothing will be touched on your database.

**Comment by thehamzan6** [comment] 2017-03-15 07:01
Everything works great. No problems so far.

**Comment by Hazaels** [comment] 2017-03-15 14:35
Here everything is working fine, too.

Thank you!

**Comment by Patriboom** [comment] 2017-03-16 01:52
When someone reassign ticket to another user, right on the page of this very issue, the new assignee will receive an email, and the this very page where the issue is shown will show the new assignation.  All this did theoricaly exist, but didn't work.  It now works.  All this was done through a pup-up, it is now done through an iframe.  That means there's no more « flash » in your face.

**Comment by Patriboom** [comment] 2017-03-29 13:06
Did anyone tried the intial topic:  « Unable to add new user »   ?

**Comment by macaulay576** [comment] 2017-03-29 17:27
I am unable to create a new issue. Fresh install, new DB. Can create users and projects succesfully, just cannot add a new issue (causes Apache to crash).
Apache Error Log:
`[Wed Mar 29 18:19:36.093173 2017] [:error] [pid 7048:tid 1856] [client ::1:64450] PHP Fatal error:  Cannot re-assign $this in C:\\xampp\\htdocs\\app\\application\\controllers\\project\\issue.php on line 291, referer: http://localhost/project/1`

**Closed** 2017-03-31 02:26 UTC
Labels: Fixed not archived yet, help wanted, Wait for your comments
